// UI copy from copy.md — Bloom brand voice
export const copy = {
  welcome: {
    wordmark: 'Bloom',
    subline: 'For the nine months that change everything.',
    primary: 'Begin',
    secondary: "We're already expecting",
  },
  dueDate: {
    eyebrow: 'WHEN IS YOUR LITTLE ONE DUE?',
    headline: "Let's count the weeks together.",
    helper: 'An estimate is perfectly fine — your provider can refine it later.',
    cta: 'Continue',
    skip: "I don't know yet",
  },
  role: {
    eyebrow: 'WHO ARE YOU IN THIS STORY?',
    headline: 'Bloom is for both of you.',
    cardA: { title: "I'm the mother", body: "You're carrying this little one. We'll walk each week with you." },
    cardB: { title: "I'm the partner", body: "You're in this too. We'll show you how to help, every single week." },
    cta: 'Start our journey',
    footer: 'You can switch roles or add your partner later in Settings.',
  },
  empty: {
    today: {
      headline: 'How is today treating you?',
      body: 'One small note a day becomes the story of nine months.',
      cta: 'Check in',
    },
    journey: {
      headline: 'Your timeline is waiting.',
      body: "Add your due date and we'll place you on the path, week by week.",
      cta: 'Add due date',
    },
    journal: {
      headline: "Nothing written yet — and that's okay.",
      body: 'The first entry can be one sentence. Even "we found out today" is enough.',
      cta: 'Write the first entry',
    },
    wishlist: {
      headline: 'A place for every tiny thing.',
      body: "Save the crib, the socks, the impossible-to-find swaddle. We'll help you find them for less.",
      cta: 'Add your first item',
    },
    foodSearch: {
      headline: "We don't know that one yet.",
      body: 'Try a simpler word — "cheese" instead of "triple-cream brie."',
    },
    cravings: {
      headline: 'No cravings confessed yet.',
      body: "When the pickle-and-ice-cream hour strikes, log it here — we'll suggest a kinder swap.",
      cta: 'Log a craving',
    },
  },
  checkinPrompts: [
    'How is your body feeling today?',
    'What are you most looking forward to this week?',
    'Did anything surprise you today?',
    'How did you sleep last night?',
    'What did you crave today — and did you give in?',
    'What are you a little nervous about right now?',
    'What made you smile today?',
    'If the baby could hear one thing from you today, what would it be?',
    "What's one thing your partner did that helped today?",
    'How are you really doing — honestly?',
  ],
  checkinPromptPartner9: "What's one thing you did today that helped her?",
  moods: ['Heavy', 'Tired', 'Okay', 'Good', 'Glowing'] as const,
  milestones: [
    { label: 'We found out', prompt: 'Where were you when you knew? Write down the small details.' },
    { label: 'First ultrasound', prompt: 'What did you see? What did it sound like?' },
    { label: 'Telling the family', prompt: 'Who cried? Who screamed? Who already knew?' },
    // Second-trimester bridge (E4): the beta cohort went quiet at weeks 13–16 —
    // these milestones keep the ladder warm exactly where we lost a user.
    { label: 'First flutters', prompt: 'Like bubbles, like a fish turning over — the first hello from inside. Where were you when you felt it?' },
    { label: 'The bump photo', prompt: "The first one where it really shows. Take it — you'll want proof of this exact week." },
    { label: 'First kick', prompt: 'Where were you sitting? What did it feel like — bubbles, taps, a fish turning over?' },
    { label: 'Finding out the sex', prompt: "Or choosing not to know — that's a story too." },
    { label: 'Halfway there', prompt: "Twenty weeks down, twenty to go. What do you know now that you didn't then?" },
    { label: 'The name conversation', prompt: "The serious contenders, the vetoes, the one you can't agree on." },
    { label: 'Nursery is done', prompt: "Take the photo. You'll forget how small everything started." },
    { label: 'Baby shower', prompt: 'Who came, what they gave, what they said.' },
    { label: 'Packing the hospital bag', prompt: 'What made the cut? What did you pack for the baby you\'ll meet so soon?' },
    { label: 'The last quiet weekend', prompt: 'What did you two do with the last days of just-us?' },
    { label: "Baby's here", prompt: "Everything. Write down everything. You'll want it all back someday." },
  ],
  today: {
    greeting: (name?: string | null) => {
      const h = new Date().getHours();
      const part = h < 12 ? 'morning' : h < 18 ? 'afternoon' : 'evening';
      return name ? `Good ${part}, ${name}` : `Good ${part}`;
    },
    sizeLine: (comparison: string) => `This week, your baby is the size of ${comparison}.`,
    checkinEyebrow: 'DAILY CHECK-IN',
    checkinQuestion: 'How are you feeling today?',
    dailyEyebrow: 'TODAY IN YOUR PREGNANCY',
    thisWeek: 'THIS WEEK',
    babyEyebrow: 'YOUR BABY',
    forYou: 'FOR YOU',
    forHer: 'FOR HER',
    forPartner: 'FOR YOUR PARTNER',
    // Week strip + day card
    weekStripEyebrow: 'YOUR WEEK, DAY BY DAY',
    weekDayLine: (week: number, day: number) => `Week ${week}, day ${day}`,
    beforeWindow: 'A quiet day just before this story begins — the counting starts soon.',
    afterWindow: 'Past the due date now — any day could be the day. Keep your provider close.',
    // "Today, for you" insights block
    forYouEyebrow: 'TODAY, FOR YOU',
    dayLine: (n: number) => `Day ${n} of your pregnancy`,
    expectEyebrow: 'WHAT TODAY MAY HOLD',
    commonEyebrow: 'COMMON AROUND NOW',
    commonAroundNow: [
      'Nausea, deep tiredness, and tender breasts are the usual companions of these weeks — for most, they soften after week 12.',
      'Energy often returns now, and the first flutters may follow soon. Round-ligament tugs and a growing bump become the new normal.',
      'Braxton Hicks practice contractions, heartburn, and lighter sleep are common as your body readies itself for the big day.',
    ],
    dayClose: "That's today — kept safe. See you tomorrow.",
  },
  compose: {
    typeLabels: { note: 'Quick note', milestone: 'Milestone', craving: 'Craving', ultrasound: 'Ultrasound' } as const,
    quickPicksEyebrow: {
      note: 'TAP TO START — OR WRITE YOUR OWN',
      milestone: 'MILESTONES — TAP TO START',
      craving: 'USUAL SUSPECTS',
      ultrasound: 'WHICH SCAN?',
    } as const,
    // Quick-note starters (Luis QA): the note type had no tap-to-start chips while
    // milestone/craving/ultrasound did — same idea, tuned for open memories.
    notePicks: [
      'Today I felt…',
      'Note to baby',
      'A name we love',
      'Something that made us laugh',
      'A small win',
      "A fear I'm letting go",
    ],
    cravingPicks: [
      'Pickles',
      'Ice cream',
      'Citrus',
      'Chocolate',
      'Something spicy',
      'Sour candy',
      'Salty fries',
      'Fresh fruit',
      'Cheese',
      'Buttered toast',
      'A milkshake',
      'Peanut butter on everything',
    ],
    ultrasoundPicks: ['Dating scan', 'Nuchal scan', 'Anatomy scan', 'Growth scan'],
    ultrasoundPhotoCta: 'Add the scan photo — it belongs right at the top.',
  },
  food: {
    segments: ['Eat well', 'Be careful', 'Cravings'] as const,
    searchPlaceholder: 'Search a food — salmon, brie, coffee…',
    benefitLine: (benefit: string) => `Supports ${benefit}`,
    doubt: 'When in doubt, ask your provider.',
    cravingPlaceholder: "I'm craving…",
    swapTitle: (craving: string) => `Craving ${craving}?`,
    swapTry: (swap: string) => `Try ${swap}`,
    disclaimer: 'Everyday guidance, not medical advice. Your provider knows you best.',
  },
  global: {
    keep: 'Keep',
    keepMemory: 'Keep this memory',
    deleteConfirm: 'Let this one go?',
    keepIt: 'Keep it',
    letItGo: 'Let it go',
    offline: "You're offline — everything is saved here, safe and sound.",
    error: "Something didn't take. Try once more?",
    signOut: 'Sign out',
    signOutConfirm: 'Your memories stay on this device.',
    weekCounter: (n: number) => `Week ${n} of 40`,
    findingAlternatives: "We're still finding lookalikes for this one",
  },
  notifications: {
    weeklyTitle: (n: number) => `Week ${n} has begun`,
    weeklyBody: (comparison: string) => `Your baby is now the size of ${comparison}. See what's growing this week.`,
    dailyTitle: 'A minute for the two of you',
    dailyBody: (name: string) => `Good evening${name ? `, ${name}` : ''} — one line for your story today?`,
  },
  onboarding: {
    tapToBegin: 'Tap to begin',
    name: {
      headline: "First — what should we call you?",
      placeholder: 'Your name',
      cta: 'Continue',
    },
    welcome: {
      hello: (name: string) => `Hello, ${name}`,
      headline: 'Nine months. One small line a day.',
      body: "Bloom turns this pregnancy into a keepsake you'll both keep forever — the weeks, the kicks, the cravings, the day everything changed.",
      cta: 'This is us — begin',
    },
    value: {
      headline: 'Two hearts, one story',
      body: 'Invite your partner and Bloom becomes yours together — you both write, you both remember.',
      cta: 'Invite my partner',
      later: "I'll do this later",
    },
    invite: {
      eyebrow: 'TWO HEARTS, ONE STORY',
      headline: 'Invite your partner',
      body: "Bloom is meant to be shared. When your partner joins, you'll see each other's check-ins, journal entries, and moments — one shared story, told by both of you.",
      cta: 'Invite my partner',
      skip: 'Not now',
    },
    firstBaby: {
      eyebrow: 'A LITTLE ABOUT YOU',
      headline: 'Is this your first baby?',
      options: ['Yes — our first', 'No — we have children'],
      saving: 'A moment…',
    },
  },
  learn: {
    headline: 'Learn',
    topics: ['All', 'Body', 'Baby', 'Birth', 'After', 'Mind'] as const,
    empty: 'Nothing here yet — check back soon.',
    saved: 'Saved',
    save: 'Save',
    minRead: (n: number) => `${n} min read`,
  },
  journey: {
    headline: 'Journey',
    weekCaps: (n: number) => `WEEK ${n}`,
    trimester: (n: number) => `Trimester ${n}`,
    pctOfJourney: (pct: number) => `${pct}% of the way there`,
    past: 'Where you\'ve been',
    next: 'Up next',
    upcomingTitle: (n: number) => `Week ${n}`,
    upcomingBody: (headline: string, comparison: string) => `${headline} — baby will be the size of ${comparison}.`,
    memoryTitle: (n: number) => `Week ${n}`,
    emptyWeek: 'A quiet week — nothing written yet.',
    addMemory: 'Add a memory',
    ctaBody: "Every week you'll both remember — the kicks, the cravings, the day everything changed.",
    cta: 'Invite your partner',
  },
  journal: {
    headline: 'Journal',
    searchPlaceholder: 'Search your story…',
    emptySearch: 'Nothing matches — try another word.',
    exportCta: 'Export your story',
    exportWorking: 'Preparing…',
    exportDevNote: 'Story export arrives with the memory book feature.',
    media: (n: number) => (n === 1 ? '1 memory' : `${n} memories`),
  },
  settings: {
    sectionProfile: 'PROFILE',
    sectionPregnancy: 'PREGNANCY',
    sectionReminders: 'REMINDERS',
    sectionPass: 'BLOOM PASS',
    sectionPartner: 'PARTNER',
    sectionAbout: 'ABOUT',
    sectionDanger: 'DANGER ZONE',
    phoneLabel: 'PHONE (OPTIONAL)',
    phonePlaceholder: '(555) 123-4567',
    phoneHint: 'Only used for sign-in and account recovery.',
    emailLabel: 'EMAIL',
    pregnancyEnded: 'This pregnancy ended — close it gently',
    deleteAccount: 'Delete my account',
    deleteHint: 'Your journal, photos, and wishlist are removed forever. There is no undo.',
    aboutPrivacy: 'Privacy policy',
    aboutTerms: 'Terms of use',
    versionLabel: (v: string) => `Bloom ${v}`,
    avatarTitle: 'Your photo',
    takePhoto: 'Take a photo',
    choosePhoto: 'Choose from library',
    useIcon: 'Pick an icon instead',
    removePhoto: 'Remove photo',
  },
  namePrompt: {
    body: "We're on a first-name basis around here — what should we call you?",
    cta: 'Save',
  },
  moment: {
    title: 'Keep this moment',
    take: 'Take a photo',
    choose: 'Choose from library',
    cancel: 'Not now',
    saved: 'Kept safe in your journal',
  },
  player: {
    weekLabel: (n: number | null) => (n ? `Week ${n}` : 'Untimed'),
  },
  danger: {
    pregnancyEndedTitle: 'Close this pregnancy?',
    pregnancyEndedBody:
      "This marks the pregnancy as ended. Your journal and photos stay exactly where they are — nothing is deleted. Whenever you're ready, you can start a new one.",
    pregnancyEndedConfirm: 'Close it gently',
    deleteConfirmTitle: 'Delete your account?',
    deleteConfirmBody:
      'This removes your account, your journal entries and photos, and your place in your household — forever. Your partner keeps their own account.',
    deleteConfirmConfirm: 'I understand — delete everything',
    deleteFinalBody: 'Last check. There is no undo, and we cannot restore any of it. Delete your account now?',
  },
  review: {
    title: 'Enjoying Bloom?',
    body: 'A few words on the App Store help another family find their nine months.',
    cta: 'Rate Bloom',
    later: 'Maybe later',
  },
  paywall: {
    eyebrow: 'THE BLOOM PREGNANCY PASS',
    headline: 'Keep every moment of these nine months.',
    subline: 'One payment for your whole pregnancy — for both of you, on both phones.',
    bullets: [
      { icon: 'people-outline', text: 'Invite your partner — two hearts writing one story' },
      { icon: 'images-outline', text: 'Unlimited photos & videos in your journal' },
      { icon: 'flash-outline', text: 'Unlimited one-tap Moments' },
      { icon: 'book-outline', text: 'The memory book, the day it ships' },
      { icon: 'heart-outline', text: 'Support a tiny team making this with love' },
    ] as const,
    passCta: (price: string) => `Get the Pregnancy Pass · ${price}`,
    passCaption: 'One payment. Your whole pregnancy. Yours forever.',
    passActive: 'Pregnancy Pass',
    passActiveBody: 'Unlocked for this pregnancy — every feature, on both phones.',
    plusEyebrow: 'OPTIONAL, FOR AFTER',
    plusTitle: 'Bloom Plus',
    plusBody: 'When the baby arrives, Plus keeps the story going — first year tracking and what comes next.',
    plusCta: (price: string) => `Add Plus · ${price}/mo`,
    plusActive: 'Plus active',
    restore: 'Restore purchase',
    restoreDone: 'Welcome back — your purchase is restored.',
    restoreNone: 'No purchase found on this Apple ID.',
    devNote: 'Purchases are not configured in this build.',
    terms: 'Terms of use',
    privacy: 'Privacy policy',
    maybeLater: 'Maybe later',
    welcome: 'Welcome to the Pass',
    welcomeBody: 'Everything is unlocked — for both of you.',
    compareEyebrow: 'FREE VS PREGNANCY PASS',
    compareFree: 'FREE',
    comparePass: 'PASS',
    compareRows: [
      { text: 'Week-by-week tracker, daily card & food guide', free: true, pass: true },
      { text: 'Daily check-ins with relief tips', free: true, pass: true },
      { text: 'Journal photos & videos', free: '25', pass: 'Unlimited' },
      { text: 'One-tap Moments', free: '10 a month', pass: 'Unlimited' },
      { text: 'Invite your partner — one shared story', free: false, pass: true },
      { text: 'The memory book, the day it ships', free: false, pass: true },
    ] as const,
    bestValue: 'BEST VALUE',
    exitEyebrow: 'BEFORE YOU GO',
    exitOfferTitle: 'A launch-week gift, just this once',
    exitOfferBody: (launch: string, full: string) =>
      `The Pregnancy Pass for ${launch} — normally ${full}. One payment covers your whole pregnancy, on both phones.`,
    exitUrgencyTitle: 'Launch pricing, while it lasts',
    exitUrgencyBody: (price: string) =>
      `The Pass is ${price} during launch — it moves to its full price after. One payment, your whole pregnancy, both phones.`,
    exitCta: (price: string) => `Get the Pass · ${price}`,
    exitDismiss: 'No thanks, maybe later',
    gatePartner: {
      title: 'This is where the Pass begins',
      body: "Inviting your partner is part of the Pregnancy Pass — one payment covers you both, on both phones, for the whole pregnancy.",
    },
    gateMoment: {
      title: 'Every moment, kept',
      body: 'Free includes 10 Moments a month. The Pass lifts every cap — unlimited Moments, unlimited journal photos, and your partner beside you.',
    },
    gateMedia: {
      title: 'Keep every photo and video',
      body: 'Free includes 25 journal photos & videos. The Pass makes your journal unlimited — every kick, every bump, every scan.',
    },
    gateCta: 'See the Pregnancy Pass',
    gateDismiss: 'Not now',
  },
  wishlist: {
    viewDeal: 'View deal',
    openLinkTitle: 'Open this link?',
    openLinkConfirm: 'Open',
    openLinkCancel: 'Not now',
    openLinkError: "Couldn't open that link",
  },
};

// Mood acknowledgments — calm, validating, ends with a practical note.
export const MOOD_ACKNOWLEDGMENTS: Record<string, string> = {
  Heavy:
    "Some days are just heavy — that's not failure, it's pregnancy. Water, rest when you can, and be gentle with yourself today.",
  Tired:
    'Growing a human is exhausting work, even when nothing shows. Early night tonight — you have our permission.',
  Okay: 'Okay is a perfectly good place to be. Steady days are the ones the story is built on.',
  Good: 'Love to hear it. Bank this feeling — write down what made today good, so future-you can visit it.',
  Glowing: 'There she is. Soak it in, take the photo, tell somebody. These are the days to remember.',
};

// Relief tips keyed by symptom — calm, practical, everyday-safe (with provider
// guidance preserved inside each). Persistent red-flag combinations (bleeding
// plus cramping, severe headache with swelling) are handled by the care line
// below, which shows on every check-in regardless of mood.
export const SYMPTOM_RELIEF_TIPS: Record<string, string> = {
  Nausea: 'Small, frequent meals and ginger tea help many moms. If you cannot keep fluids down for 24 hours, call your provider.',
  Fatigue: 'Your body is building a placenta — rest is productive. A 20-minute nap or an early bedtime counts as a win.',
  Heartburn: 'Try smaller meals and avoid lying down right after eating. Ask your provider before any antacid.',
  Headache: 'Hydrate, rest your eyes, and check posture. Severe or sudden headaches deserve a same-day call.',
  Swelling: 'Feet up, water in, rings off early. Sudden face or hand swelling is worth a call to your provider.',
  Cramping: 'Gentle stretching and warmth can help. Cramping with bleeding should always be checked promptly.',
  Insomnia: 'A pillow between the knees and a cooler room help. Screens off an hour before bed makes a real difference.',
  Backache: 'Watch posture when sitting, and try a pregnancy pillow at night. A warm (not hot) compress can ease the ache.',
  'Dizzy spells':
    'Rise slowly and keep a snack nearby — blood pressure dips are common. Lying on your left side helps blood flow.',
  'Tender breasts':
    'A supportive sleep bra makes nights easier. Tenderness usually eases after the first trimester.',
  'Brain fog':
    'Real, and hormone-driven — lists are your friend. It lifts after delivery, promise.',
  'Short of breath':
    'A growing uterus presses on the diaphragm — normal in short bursts. Sudden or severe breathlessness deserves a call.',
};
